## Import the Libraries

In [19]:
import pandas as pd
import numpy as np

## Load the dataset

In [20]:
path = './Train.csv'
df = pd.read_csv(path)
df[df['leftover_inventory']<0]

,sku_name,starting_inventory,sellin,sellin_channel_1,sellin_channel_2,sellin_channel_3,sellin_channel_4,sellin_channel_5,sellin_channel_6,sellin_channel_7,sellin_channel_8,sellout,onhand_inventory,leftover_inventory,sellout_channel_1,sellout_channel_2,sellout_channel_3,sellout_channel_4,sellout_channel_5,sellout_channel_6,sellout_channel_7,sellout_channel_8,sellout_channel_9,sellout_channel_10,onhand_inventory_channel_1,onhand_inventory_channel_2,onhand_inventory_channel_3,onhand_inventory_channel_4,onhand_inventory_channel_5,onhand_inventory_channel_6,onhand_inventory_channel_7,onhand_inventory_channel_8,onhand_inventory_channel_9,onhand_inventory_channel_10,price,month,year,product_lifecycle_stage,FLAG100,disc_month,cum_disc,CAT_GENDER_BOTH,CAT_GENDER_MEN,CAT_GENDER_WOMEN,Weeks
6,YOSHUANEMARX,0,43559,0,6078,34442,0,0,0,0,0,65845,332264,-22286,0,1013,56728,4052,1013,0,0,0,0,3039,0,31403,254263,5065,21273,0,0,4052,0,16208,155,7,2018,W,0.000000,0,0,0,0,1,1
7,YOSHUANEMARX,0,22286,0,0,17221,4052,0,0,0,0,64832,283640,-42546,0,0,62806,1013,0,0,0,0,0,1013,0,30390,206652,8104,19247,0,0,4052,0,15195,155,8,2018,W,0.000000,0,0,0,0,1,0
11,YOSHUANEMARX,0,50650,1013,0,37481,0,0,10130,0,0,81040,261354,-30390,0,0,64832,3039,3039,6078,0,2026,0,2026,0,28364,199561,3039,10130,0,0,1013,0,19247,155,12,2018,W,0.054154,0,0,0,0,1,1
13,YOSHUANEMARX,0,19247,0,0,13169,0,0,5065,0,0,30390,297822,-11143,0,5065,20260,1013,0,1013,0,2026,0,1013,0,55715,203613,2026,10130,0,0,11143,0,15195,155,2,2019,W,0.100000,1,1,0,0,1,0
15,YOSHUANEMARX,0,25325,17221,0,0,0,0,8104,0,0,37481,246159,-12156,0,5065,19247,7091,1013,4052,0,1013,0,0,0,41533,17221,136755,14182,0,2026,22286,0,12156,155,4,2019,W,0.123413,1,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44901,ABEAHAMASHL,560189,24312,7091,0,0,0,0,1013,0,9117,40520,184366,-16208,37481,0,1013,1013,1013,0,0,0,0,0,151950,0,3039,25325,1013,0,0,1013,0,2026,149,5,2021,W,0.000000,0,0,0,0,1,1
44903,ABEAHAMASHL,406213,34442,6078,0,0,0,0,4052,0,21273,38494,396083,-4052,36468,0,-1013,0,1013,4052,0,0,0,-2026,386966,0,2026,6078,0,0,0,0,0,1013,149,7,2021,W,0.333333,0,0,0,0,1,0
44904,ABEAHAMASHL,375823,38494,0,0,0,24312,0,14182,0,0,56728,274523,-18234,34442,0,0,8104,0,13169,0,0,0,1013,253250,0,2026,18234,0,0,0,0,0,1013,149,8,2021,W,0.400000,1,1,0,0,1,1
44905,ABEAHAMASHL,400135,29377,1013,0,0,1013,0,6078,0,21273,65845,123586,-36468,55715,0,-1013,6078,0,5065,0,0,0,0,111430,0,2026,9117,0,0,0,0,0,1013,149,9,2021,W,0.000000,0,1,0,0,1,0
44906,ABEAHAMASHL,410265,18234,0,0,0,1013,0,17221,0,0,29377,100287,-11143,11143,0,0,2026,0,16208,0,0,0,0,95222,0,0,5065,0,0,0,0,0,0,149,10,2021,W,0.452381,1,1,0,0,1,1

## Split the dataset in to train and test
Our problem revolves around demand forecasting and inventory optimization, where we aim to predict the stock requirements for the upcoming quarter using historical data. To achieve this, the dataset has been divided based on month and year information. 
- The **train dataset** includes data from January 2016 to July 2021.  
- The **test dataset**, which represents completely unseen data (akin to production data), spans from August 2021 to October 2021. This test set will be used for evaluating predictions, model performance, and analyzing business impact.

In [18]:
# Define training and testing ranges
train_year_start, train_year_end = 2016, 2021
train_month_end = 7
test_year = 2021
test_month_start, test_month_end = 8, 10

# Create training set
train_set = df[
    ((df['year'] > train_year_start) & (df['year'] < train_year_end)) |  # Full years in range
    ((df['year'] == train_year_start) & (df['month'] >= 1)) |           # Start year
    ((df['year'] == train_year_end) & (df['month'] <= train_month_end)) # End year
]

# Create testing set
test_set = df[
    (df['year'] == test_year) & 
    (df['month'] >= test_month_start) & 
    (df['month'] <= test_month_end)
]

In [13]:
train_set.shape

(43018, 45)

In [14]:
test_set.shape

(1889, 45)

In [15]:
train_set.head(5)

,sku_name,starting_inventory,sellin,sellin_channel_1,sellin_channel_2,sellin_channel_3,sellin_channel_4,sellin_channel_5,sellin_channel_6,sellin_channel_7,sellin_channel_8,sellout,onhand_inventory,leftover_inventory,sellout_channel_1,sellout_channel_2,sellout_channel_3,sellout_channel_4,sellout_channel_5,sellout_channel_6,sellout_channel_7,sellout_channel_8,sellout_channel_9,sellout_channel_10,onhand_inventory_channel_1,onhand_inventory_channel_2,onhand_inventory_channel_3,onhand_inventory_channel_4,onhand_inventory_channel_5,onhand_inventory_channel_6,onhand_inventory_channel_7,onhand_inventory_channel_8,onhand_inventory_channel_9,onhand_inventory_channel_10,price,month,year,product_lifecycle_stage,FLAG100,disc_month,cum_disc,CAT_GENDER_BOTH,CAT_GENDER_MEN,CAT_GENDER_WOMEN,Weeks
0,YOSHWARDTERR,0,1013,0,0,0,1013,0,0,0,0,1013,0,0,0,0,0,1013,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,95,7,2016,U,0.000000,0,0,0,1,0,1
1,YOSHWARDTERR,0,2026,0,0,0,2026,0,0,0,0,0,1013,2026,0,0,0,0,0,0,0,0,0,0,0,0,0,1013,0,0,0,0,0,0,95,2,2017,U,0.000000,0,0,0,1,0,0
2,YOSHWARDTERR,0,1013,0,0,0,1013,0,0,0,0,1013,0,0,0,0,0,1013,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,95,5,2017,U,0.000000,0,0,0,1,0,0
3,YOSHUANEMARX,0,320108,4052,40520,240081,4052,6078,18234,0,0,56728,259328,263380,0,1013,43559,0,0,12156,0,0,0,0,0,39507,190444,6078,0,0,0,0,0,23299,155,4,2018,W,0.270966,1,1,0,0,1,1
4,YOSHUANEMARX,0,132703,2026,0,81040,3039,25325,18234,0,0,90157,270471,42546,0,3039,69897,6078,0,8104,0,0,0,3039,0,36468,202600,3039,0,0,0,7091,0,21273,155,5,2018,W,0.063004,0,1,0,0,1,0

In [16]:
test_set.head(5)

,sku_name,starting_inventory,sellin,sellin_channel_1,sellin_channel_2,sellin_channel_3,sellin_channel_4,sellin_channel_5,sellin_channel_6,sellin_channel_7,sellin_channel_8,sellout,onhand_inventory,leftover_inventory,sellout_channel_1,sellout_channel_2,sellout_channel_3,sellout_channel_4,sellout_channel_5,sellout_channel_6,sellout_channel_7,sellout_channel_8,sellout_channel_9,sellout_channel_10,onhand_inventory_channel_1,onhand_inventory_channel_2,onhand_inventory_channel_3,onhand_inventory_channel_4,onhand_inventory_channel_5,onhand_inventory_channel_6,onhand_inventory_channel_7,onhand_inventory_channel_8,onhand_inventory_channel_9,onhand_inventory_channel_10,price,month,year,product_lifecycle_stage,FLAG100,disc_month,cum_disc,CAT_GENDER_BOTH,CAT_GENDER_MEN,CAT_GENDER_WOMEN,Weeks
47,YOSHTLYNYOSHZZ,329225,54702,43559,0,0,0,0,5065,1013,0,46598,309978,8104,20260,0,11143,0,5065,4052,2026,0,0,4052,210704,0,50650,6078,15195,0,2026,0,0,25325,149,8,2021,N,0.000000,0,0,0,1,0,1
48,YOSHTLYNYOSHZZ,114469,221847,82053,91170,16208,0,20260,6078,2026,0,60780,286679,161067,37481,0,6078,2026,6078,4052,0,0,0,5065,188418,0,55715,4052,15195,0,2026,0,0,21273,149,9,2021,N,0.233333,1,1,0,1,0,0
49,YOSHTLYNYOSHZZ,156002,163093,122573,30390,0,0,0,2026,7091,0,33429,269458,129664,17221,0,7091,0,7091,2026,0,0,0,0,151950,0,42546,3039,44572,0,0,0,0,27351,149,10,2021,N,0.000000,0,1,0,1,0,1
136,YOSHRENECARL,1490123,204626,128651,47611,16208,0,0,3039,8104,0,111430,742529,93196,90157,0,15195,0,1013,3039,1013,0,0,1013,504474,0,187405,10130,14182,0,4052,0,0,22286,129,8,2021,N,0.000000,0,0,0,0,1,1
137,YOSHRENECARL,1349316,961337,437616,486240,6078,0,0,16208,14182,0,126625,735438,834712,96235,0,12156,0,2026,13169,2026,0,0,1013,506500,0,161067,14182,20260,0,10130,0,0,23299,129,9,2021,N,0.300000,1,1,0,0,1,0

In [17]:
# Export the data to CSV fILE 

# Train File
train_set.to_csv("NEW-TRAIN-SPLIT.csv",index=False)

# Test File
test_set.to_csv("NEW-TEST-SET.csv",index=False)